- services/promo.js
Promo codes are no longer case sensitive
> fix promo code sensitive to insensitive

- backoffice/app/attribute/views/attribute-detail.html
- backoffice/app/client/client.controllers.js
- backoffice/app/client/views/client-list.html
- backoffice/js/directives.js
- orm/schemas/productsSchema.js
- services/attribute.js
- services/products.js
- services/rules.js
- themes/default_theme/pages/product.js
- utils/utils.js
Removed attributes and operator that where in french to english and the convertor that where associated to them
> Remove historical attributes and operator

- backoffice/app/staticPage/staticPage.controllers.js
- backoffice/app/staticPage/staticPage.services.js
- backoffice/app/staticPage/views/staticPage-detail.html
Add a hook to static pages. Useful for the SEO module
> [Feature]  add hook to static page

- backoffice/app/medias/medias.controllers.js
- backoffice/app/medias/views/modals/copy_link.html
- backoffice/assets/translations/en/medias.json
- backoffice/assets/translations/fr/medias.json
- routes/index.js
- services/medias.js
Allow to crop image instead of create an alpha zone around the image using the route
images/medias/{options}/{image_id}/{filename}
example : images/medias/200x200-100-crop-top-left/5d444fa2ede1945f6602892f/bannieretshirt.jpg
> Crop image in Url 

- backoffice/app/product/product.controllers.js
- backoffice/app/product/views/templates/nsProductGeneral.html
- backoffice/app/productSimple/simpleProduct.controllers.js
- backoffice/app/productSimple/views/simpleProduct.html
- backoffice/assets/translations/fr/update.json
- backoffice/js/directives.js
- backoffice/views/templates/nsButtons.html
[Fix] spelling mistake
[Feature] use the feature "moreButtons" to add button to product
[Fix] change coherence product in the new feature
please don't criticize my double ternary operator (in backoffice/views/templates/nsButtons.html)
: )
> [Feature] add moreButtons to Ns button directive

- backoffice/app/picto/views/picto-details.html
- backoffice/app/product/views/templates/nsProductPrice.html
- backoffice/assets/translations/en/picto.json
- backoffice/assets/translations/en/product.json
- backoffice/assets/translations/fr/picto.json
- backoffice/assets/translations/fr/product.json
[Fix] tooltip for price
add tooltip in two pages and remove one ugly tooltip
> [Feature] add tooltip for picto

- backoffice/app/attribute/views/attribute-detail.html
- backoffice/assets/translations/en/attribute.json
- backoffice/assets/translations/en/product.json
- backoffice/assets/translations/fr/attribute.json
- backoffice/assets/translations/fr/product.json
- middleware/server.js
- orm/schemas/attributesSchema.js
- orm/schemas/productsSchema.js
- services/attribute.js
si un attribut est marqué comme non visible, il n'est pas retourné au front (React), mais l'ai pour l'admin
> [feature] attribute visibility

- backoffice/app/picto/picto.controllers.js
- backoffice/app/picto/picto.services.js
- backoffice/app/picto/views/picto-details.html
- backoffice/assets/translations/en/picto.json
- backoffice/assets/translations/fr/picto.json
- routes/pictos.js
- services/rules.js
[Feature] add translate for picto
/!\ Normaly work if my previuous Pull request is merged
> [Feature] add pictorisation for Picto Page

- backoffice/app/attribute/views/attribute-detail.html
- backoffice/app/picto/views/picto-details.html
- backoffice/assets/translations/en/attribute.json
- backoffice/assets/translations/en/picto.json
- backoffice/assets/translations/fr/attribute.json
- backoffice/assets/translations/fr/picto.json
I Just change the location of the ti (it was on the wrong page)
> [Fix] correct the wrong place for toolTip

- backoffice/app/client/client.controllers.js
- backoffice/app/product/views/templates/nsProductPhoto.html
- backoffice/app/productSimple/simpleProduct.controllers.js
- backoffice/app/promo/promo.controllers.js
- backoffice/views/templates/nsButtons.html
[Fix] switch 'moreText' by 'icon'
> [Fix] location of moreButtons

- backoffice/app/mail/mail.controllers.js
- backoffice/app/mail/views/mail-detail.html
The icon works only if my previous pull request is accepted
> [Fix] button in additionalButtons

- backoffice/app/picto/views/picto-details.html
change the choix into a table (more convenient for responsive)
last change in the file -> I commented an unnecessary css rule
> [fix] display of the choice

- backoffice/app/client/client.controllers.js
- backoffice/app/picto/picto.controllers.js
- backoffice/app/productSimple/simpleProduct.controllers.js
- backoffice/views/templates/nsButtons.html
add ng-if in html
add attribut isDisplayed to use ng-if
comment a console.log()
> Fix more button display

- backoffice/app/productBundle/bundleProduct.controllers.js
- backoffice/app/productBundle/views/bundleProduct.html
- backoffice/app/productSimple/simpleProduct.controllers.js
- backoffice/app/productSimple/views/simpleProduct.html
- backoffice/app/promo/promo.controllers.js
- backoffice/assets/translations/en/ns.json
- backoffice/assets/translations/en/product.json
- backoffice/assets/translations/fr/ns.json
- backoffice/assets/translations/fr/product.json
- backoffice/js/directives.js
- backoffice/views/templates/nsButtons.html
> Remove duplicate button

- services/promo.js
Calculate ATI from ET after discount if condition is `Aet`
Calculate ET from ATI after discount if condition is `Aati`
Calculate ATI from ET after discount if condition is `P`
> calculate ATI from ET

- backoffice/app/themes/themes.controllers.js
- backoffice/app/themes/views/modals/themes-new.html
- backoffice/app/themes/views/themes.html
- backoffice/js/directives.js
[fix] add toastService to directive
[fix] change place to upload
[feature] add modal open
> [fix] New theme upload

- backoffice/app/app.js
- backoffice/app/config/config.controllers.js
- backoffice/app/config/config.services.js
- backoffice/app/config/views/environment.config.html
- backoffice/app/modules/modules.controllers.js
- backoffice/app/order/order.controllers.js
- backoffice/app/product/product.controllers.js
- backoffice/app/product/product.directives.js
- backoffice/app/product/views/templates/nsProductPrice.html
- backoffice/app/shipment/shipment.controllers.js
- backoffice/app/shipment/views/shipment-detail.html
- backoffice/app/stock/stock.controllers.js
- backoffice/app/stock/stock.html
- backoffice/app/system/system.controllers.js
- backoffice/app/system/system.services.js
- backoffice/app/system/views/system.html
- backoffice/app/themes/themes.controllers.js
- backoffice/app/themes/views/themes.html
- backoffice/app/update/update.controllers.js
- backoffice/app/update/views/updateHome.html
- orm/schemas/configurationSchema.js
- routes/config.js
- routes/system.js
- routes/themes.js
- services/config.js
- services/system.js
Instead of using **params** in the query, we could now use the PostBody, it's easier to get configuration values as the schemas was not mutated
❗ **hubrise as i know is the only module that rely on old configuration query** ❗
> Rework configuration routes

- backoffice/app/app.js
- middleware/authentication.js
- middleware/server.js
- routes/cart.js
- routes/cmsBlocks.js
- routes/component.js
- routes/orders.js
- routes/products.js
- routes/promo.js
- routes/reviews.js
- routes/statics.js
- services/cart.js
- services/categories.js
- services/component.js
- services/orders.js
- services/promo.js
Store user in req.info for each api request if header **Authorization** is provided and correct
> Retrieve user

- backoffice/app/product/product.controllers.js
- backoffice/app/product/product.directives.js
- backoffice/app/product/views/templates/nsProductCategories.html
- backoffice/app/productBundle/bundleProduct.controllers.js
- backoffice/app/productBundle/views/bundleProduct.html
- backoffice/app/productSimple/simpleProduct.controllers.js
- backoffice/app/productSimple/views/simpleProduct.html
- backoffice/app/productVirtual/product-virtual.controllers.js
- backoffice/app/productVirtual/views/product-virtual.html
Create a generic file and a directive for the category tab
Files added : 
- `product.directives.js`           -> add the directive for `nsProductCategories`
- `product.controllers.js`         -> add the controller for `nsProductCategories`
- `nsProductCategories.html` ->  add the template for `nsProductCategories`
---
Use directive / change to directive in : 
- simple product
- bundle product
- virtual product
> [product] create generic file for category tab

- backoffice/app/category/category.controllers.js
- backoffice/app/category/category.routes.js
- backoffice/app/category/views/category-detail.html
- backoffice/app/category/views/category-list.html
- backoffice/assets/translations/en/category.json
- backoffice/assets/translations/fr/category.json
- Change the move option for categories
- Create a new page and a new route for category detail
> Change dynamic of categories page

- backoffice/assets/translations/en/global.json
- backoffice/assets/translations/fr/global.json
- backoffice/js/directives.js
- backoffice/js/filters.js
- backoffice/views/templates/nsStatusLabel.html
The directive wasn't working correctly :
- sometimes there was a translation code
- sometimes just a word :( 
Now the directive use only translation code :)
Directive `nsStatusLabel` is used in :
- `client-detail.html` (ok)
- `order-list.html` (ok)
- `payment-list.html` (ok)
- `picto-list.html` (ok)
> [fix] change the directive

- backoffice/app/category/category.controllers.js
- backoffice/app/category/views/category-list.html
Category List now support displayOrder :
- autocheck if the order is correct
- place the correct "displayOrder" to the category after a move
Category now support move of root Categories
- you can now change the order of root categories
> Category Controller : change and use displayOrder and more

- backoffice/app/category/category.controllers.js
- backoffice/app/category/views/category-detail.html
- backoffice/assets/translations/en/category.json
- backoffice/assets/translations/fr/category.json
Two options  :
- get products of the category
- get others products, not in the category
> Change the controller to get correct products

- backoffice/app/product/product.controllers.js
- backoffice/app/product/product.directives.js
- backoffice/app/product/views/modals/selectproducts.html
- backoffice/app/product/views/templates/nsProductsList.html
global && better directive !
Used in : 
- backoffice > products > `associed products`
- backoffice > products > bundleProduct > composition
- plugin `google-shopping-aquila`
> Better ns-product-list directive

- test/promo2.test.js
- test/utils/createCart.js
- test/utils/createProduct.js
- test/utils/createPromo.js
- test/utils/testPromo.js
To run them, you can do : 
```sh
PORT=3011 npm -s run test -- -g "Promo Ap"
```
> For only new tests
or
```sh
PORT=3011 npm -s run test
```
> For all tests
> [feature] add promos tests

- documentations/swagger/components/paths/index.js
- documentations/swagger/components/paths/suppliers.json
- documentations/swagger/components/paths/trademarks.json
Added :
- trademarks
- suppliers
> Add to swagger

- documentations/swagger/description.md
- documentations/swagger/makeSwaggerDesc.js
- documentations/swagger/swagger.js
- test/promo2.test.js
- test/utils/createCart.js
- test/utils/createProduct.js
- test/utils/createPromo.js
- test/utils/testPromo.js
Auto-make the swagger description from the file `description.md`
> Make swagger desc

- backoffice/app/category/category.controllers.js
- backoffice/app/category/category.directives.js
- backoffice/app/category/category.module.js
- backoffice/app/category/views/category-list.html
- backoffice/app/category/views/templates/ns-category-list-directives.html
- backoffice/app/product/product.controllers.js
- backoffice/app/product/views/templates/nsProductCategories.html
- backoffice/views/ejs/layout.ejs
new directive display display categories and check some
With callback for :
- `categoryIsChecked` -> when the category is already checked
- `categoryIsDisabled` -> when the category is already disabled
- `categoryOnClick` -> when we check the categorie
Applied in Products > Linked Categories
> [feature] new directive : ns-category-list-directives

- services/seo.js
Change `sitemap.xml` generation
- change a `urlset` tag to accept `xhtml:link` (the browser can now parse it) 
- remove useless regex by better using the package `js2xmlparser`
> Change sitemap generation

- routes/admin.js
- routes/backoffice.js
- routes/index.js
- Separate admin and api
- loadDynamicRoutes :
- first readdir and filter
- then load routes
- add a message to know the time of loading
> Better routes loading

- services/modules.js
Eslint don't link double ternary
I change the double ternary with some `||` logical or
Is it correct ?
> Change double ternary

- services/mail.js
- utils/medias.js
In reference of that comment https://github.com/AquilaCMS/AquilaCMS/commit/ae397ee7e0d3d8acc6bcd454ff034f35876ccb56#r54801901
- change `pathAttchments` by `attachments`
- protect function `deleteFile` and `deleteFolder`
Remember that attachments need to be object, minimal is :
```js
const attachments = [
{
path : 'my/path/file.pdf', // the folder under "upload directory"
name : {
mimetype     : 'application/pdf',
originalname : 'facture'
}
}
]
```
> Attachments and safe function

- backoffice/app/config/config.services.js
- backoffice/app/system/system.controllers.js
- backoffice/app/system/system.directives.js
- backoffice/app/system/views/system.html
- routes/config.js
- services/config.js
L'uplaods de certificat pour le SSL ne fonctionne pas
> [Aquila] BO/API : Certificat SSL
